kind: EventStreams
apiVersion: eventstreams.ibm.com/v1beta2
metadata:
  annotations:
    eventstreams.ibm.com/apicurio-registry-version: '>=2.4'
    argocd.argoproj.io/sync-wave: "1"
  name: es-light
spec:
  version: latest
  license:
    accept: true
    use: CloudPakForIntegrationNonProduction
  adminApi: {}
  adminUI: {}
  apicurioRegistry: {
    replicas: 0
  }
  collector: {}
  restProducer: {
    replicas: 0
  }
  security:
    internalTls: NONE
  strimziOverrides:
    kafka:
      replicas: 1
      storage:
        type: ephemeral
      config:
        inter.broker.protocol.version: '3.4'
        offsets.topic.replication.factor: 1
        transaction.state.log.min.isr: 1
        transaction.state.log.replication.factor: 1
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: external
          port: 9094
          tls: true
          type: route
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: es-light-metrics-config
    zookeeper:
      replicas: 1
      storage:
        type: ephemeral
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: es-light-metrics-config
  requestIbmServices:
    iam: false
    monitoring: false