apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "3"
  name: mq-source-connector
  labels:
    eventstreams.ibm.com/cluster: my-connect-cluster
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  config:
    mq.channel.name: MVP.APP.SVRCONN
    mq.record.builder.key.header: JMSMessageID
    value.converter: org.apache.kafka.connect.storage.StringConverter
    mq.user.name: 1001
    mq.queue.manager: QM1
    mq.queue: APP.EVENTS.QUEUE
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder
    topic: TSOURCE
    key.converter: org.apache.kafka.connect.storage.StringConverter
    mq.user.password: ''
    mq.message.body.jms: true
    mq.connection.name.list: qm1-ibm-mq.demo-01.svc(1414)
  tasksMax: 1
