kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "0"
  name: qm-settings
data:
  mq.mqsc: |
    DEFINE CHANNEL(MVP.APP.SVRCONN) CHLTYPE(SVRCONN)
    SET CHLAUTH(MVP.APP.SVRCONN) TYPE(BLOCKUSER) USERLIST('nobody')
    SET CHLAUTH('*') TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(NOACCESS)
    SET CHLAUTH(MVP.APP.SVRCONN) TYPE(ADDRESSMAP) ADDRESS('*') USERSRC(CHANNEL) CHCKCLNT(REQUIRED)
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) ADOPTCTX(YES)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE QLOCAL(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    DEFINE QLOCAL(APP.1.Q) MAXDEPTH(100) REPLACE
    DEFINE QLOCAL(APP.QUEUE) STRMQOS(MUSTDUP) STREAMQ(APP.EVENTS.QUEUE) MAXDEPTH(100) REPLACE
    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('1001') AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE(APP.EVENTS.QUEUE) OBJTYPE(QUEUE) PRINCIPAL('1001') AUTHADD(ALLMQI)
